name: brasil_cripto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  hard_analyser: ^1.9.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
